Фадеев Родион Владимирович, Б05-201, 2, D, 70978724
SFx57/Algo_Course pull request #5
Opened 2022-10-16 22:19 UTC by SFx57

2022-10-18 11:26 UTC, orenty7 requested changes

2022-10-18 11:26 UTC, orenty7 commented on D2.cpp
> +  if (mini.empty()) {
https://youtube.com/watch?v=ZzwWWut_ibU

2022-10-18 11:26 UTC, orenty7 commented on D2.cpp
> +    for (int i = 1; i != size; ++i) {
For по факту просто ищет нужный индекс. Этот код следует переписать так
```
int idx;
for (idx = 1; idx != size; idx++) {
  if (a > mini[idx]) {
    break;
  }
}
for (int j = 0; j != idx; ++j) {
  mini[j] = mini[j + 1];
}
mini[idx - 1] = a;
```

2022-10-18 11:26 UTC, orenty7 commented on D2.cpp
> +    if (size < k || mini[0] > a) {
Эту проверку по-хорошему бы тоже в функцию запихнуть

2022-10-18 11:26 UTC, orenty7 commented on D2.cpp
> +long long n;
Пачка глобальных переменных это сразу бан. Нужно или организовать их в структуру, или спрятать в функции. Например, n нигде, кроме main не используется. Нет смысла делать её глобальной

2022-12-07 22:47 UTC, VladislavHacker commented on main.cpp
> +long long n;
ну и кринжатина

2022-12-07 22:47 UTC, VTroyanGolovyan approved these changes

2022-12-07 22:48 UTC, closed without merging