Фадеев Родион Владимирович, Б05-201, 2, J, 71340120
SFx57/Algo_Course pull request #7
Opened 2022-10-16 22:25 UTC by SFx57

2022-10-18 11:09 UTC, orenty7 requested changes

2022-10-18 11:09 UTC, orenty7 commented on J2.cpp
> +void Delete(Node* root) {
Эти функции не имеют ничего общего с объявлениями внутри структуры. В таких случаях нужно указывать к какому классу они принадлежат. В твоём случае нужно дописать`Node::` к названию функции

2022-10-18 11:09 UTC, orenty7 commented on J2.cpp
> +  int h;
Переменная в структуре, будет использоваться много. Нужно нормальное название

2022-10-18 11:09 UTC, orenty7 commented on J2.cpp
> +  int key;
По-хорошему, нужно завести класс AVL, внутри которого будет структура Node (смотреть код с семинара)
В твоём случае, хотя бы сделай их приватными, чтобы нельзя было испортить дерево извне

2022-10-18 11:09 UTC, orenty7 commented on J2.cpp
> +  n->left = (m->right == 0 ? 0 : m->right);
Лишняя тернарка. Этот код эквивалентен `m->right`

2022-10-18 11:09 UTC, orenty7 commented on J2.cpp
> +  n->right = (m->left == 0 ? 0 : m->left);
Аналогично

2022-12-07 22:49 UTC, VTroyanGolovyan commented
где правки

2022-12-07 22:50 UTC, VladislavHacker requested changes

2022-12-07 22:50 UTC, VladislavHacker commented on main.cpp
> +  n->left = (m->right == 0 ? 0 : m->right);
ты рофлишь над нами?

2022-12-20 20:28 UTC, closed without merging